variable "vasso" {}
variable "vmbastion" {}
variable "vbassub" {}
variable "vnic" {}
variable "vnsg" {}
variable "vpip" {}
variable "vrgs" {}
variable "vsubnet" {}
variable "vmlinux" {}
variable "vnet" {}
